"""initial schema

Revision ID: 942e2d319f32
Revises: 
Create Date: 2026-04-02 07:42:57.450169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '942e2d319f32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('terraform_plan', 'terraform_state', 'aws_live', name='sourcetype'), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='ingestionstatus'), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('resource_type', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('terraform_plan', 'terraform_state', 'aws_live', name='sourcetype'), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('change_action', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resources_external_id_type', 'resources', ['external_id', 'resource_type'], unique=False)
    op.create_index('ix_resources_resource_type', 'resources', ['resource_type'], unique=False)
    op.create_index('ix_resources_source', 'resources', ['source'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.Enum('orphan', 'drift', 'exposure', 'circular_dep', 'critical_node', name='findingtype'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_resource_id', 'findings', ['resource_id'], unique=False)
    op.create_index('ix_findings_severity', 'findings', ['severity'], unique=False)
    op.create_index('ix_findings_type', 'findings', ['finding_type'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_resource_id', sa.UUID(), nullable=False),
    sa.Column('to_resource_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('runs_in', 'member_of', 'attached_to', 'grants_access_to', 'routes_to', 'encrypted_by', 'depends_on', 'created_by_module', name='relationshiptype'), nullable=False),
    sa.Column('source', sa.Enum('terraform_plan', 'terraform_state', 'aws_live', name='sourcetype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relationships_from', 'relationships', ['from_resource_id'], unique=False)
    op.create_index('ix_relationships_to', 'relationships', ['to_resource_id'], unique=False)
    op.create_index('ix_relationships_type', 'relationships', ['relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationships_type', table_name='relationships')
    op.drop_index('ix_relationships_to', table_name='relationships')
    op.drop_index('ix_relationships_from', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('ix_findings_type', table_name='findings')
    op.drop_index('ix_findings_severity', table_name='findings')
    op.drop_index('ix_findings_resource_id', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_resources_source', table_name='resources')
    op.drop_index('ix_resources_resource_type', table_name='resources')
    op.drop_index('ix_resources_external_id_type', table_name='resources')
    op.drop_table('resources')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
